POST {{url}}/student
Content-Type: application/json

{
  "name": "Roman",
  "mood": "Inspired"
}

###

GET {{url}}/student/moods
Accept: application/json

###
GET {{url}}/student


###

GET {{url}}/api-docs


###

PUT {{url}}/film
Content-Type: application/json

{"title":  "The Pain",
"genre":  "ADVENTURE",
"studentId":  2}

###
GET {{url}}/film